"""empty message

Revision ID: 130656bf4551
Revises: 3fc04250e661
Create Date: 2019-11-06 17:44:37.381919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130656bf4551'
down_revision = '3fc04250e661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_washing', sa.Column('cycleComplete', sa.String(length=120), nullable=True))
    op.add_column('current_washing', sa.Column('machineNumber', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_washing', 'machineNumber')
    op.drop_column('current_washing', 'cycleComplete')
    # ### end Alembic commands ###
